In [3]:
import pandas as pd
import numpy as np

In [4]:
data=pd.read_excel("C:/Users/RUCHI/Downloads/Simmons.xls")
data

Customer  Spending  Card  Coupon
0          1     2.291     1       0
1          2     3.215     1       0
2          3     2.135     1       0
3          4     3.924     0       0
4          5     2.528     1       0
..       ...       ...   ...     ...
95        96     3.318     0       0
96        97     2.421     1       0
97        98     6.073     0       0
98        99     2.630     1       0
99       100     3.411     0       1

[100 rows x 4 columns]

In [5]:
data.describe()    #Card and coupon holds the values 0 and 1 and hence their means are near about 0.5

Customer    Spending        Card      Coupon
count  100.000000  100.000000  100.000000  100.000000
mean    50.500000    3.333790    0.500000    0.400000
std     29.011492    1.741298    0.502519    0.492366
min      1.000000    1.058000    0.000000    0.000000
25%     25.750000    2.059000    0.000000    0.000000
50%     50.500000    2.805500    0.500000    0.000000
75%     75.250000    4.468250    1.000000    1.000000
max    100.000000    7.076000    1.000000    1.000000

In [6]:
data['Coupon'].unique()

array([0, 1], dtype=int64)

In [7]:
data['Coupon'].value_counts()

0    60
1    40
Name: Coupon, dtype: int64

In [8]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [9]:
x = data[['Card','Spending']]
y = data['Coupon'].values.reshape(-1,1)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.25,random_state=42)

In [10]:
len(x_train),len(y_train),len(x_test),len(y_test)

(75, 75, 25, 25)

# This is logistic regression

In [11]:
Lreg = LogisticRegression(solver='lbfgs')
Lreg.fit(x_train,y_train.ravel())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [12]:
y_predict = Lreg.predict(x_test)
y_predict

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0], dtype=int64)

In [13]:
y_predict_train = Lreg.predict(x_train)
y_predict_train

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0], dtype=int64)

In [16]:
y_prob_train = Lreg.predict_proba(x_train)[:,1]
y_prob_train.reshape(1,-1)

array([[0.49622117, 0.32880793, 0.44329114, 0.33320924, 0.41456465,
        0.32890329, 0.3975043 , 0.66921229, 0.25844531, 0.63672372,
        0.29274386, 0.28466974, 0.5159296 , 0.41992276, 0.24342356,
        0.528514  , 0.47965107, 0.52805789, 0.33191449, 0.27457435,
        0.49179296, 0.63261616, 0.24690181, 0.47089452, 0.27842076,
        0.41663875, 0.36155602, 0.49970327, 0.23621636, 0.37860052,
        0.48809323, 0.28877877, 0.28563859, 0.37231882, 0.65309742,
        0.43807264, 0.33638478, 0.40406607, 0.23431177, 0.37282384,
        0.49970327, 0.39768396, 0.32880793, 0.25782472, 0.47393834,
        0.42878861, 0.26520939, 0.33320924, 0.54682499, 0.45446086,
        0.44326597, 0.4965167 , 0.60065954, 0.38989654, 0.49149447,
        0.27414424, 0.27785686, 0.67464141, 0.28195004, 0.48593427,
        0.38633222, 0.31373499, 0.42810085, 0.27418723, 0.44371771,
        0.41629601, 0.642004  , 0.6571001 , 0.44068025, 0.28195004,
        0.40217015, 0.43807264, 0.50977653, 0.57

In [17]:
y_prob = Lreg.predict_proba(x_test)[:,1]
y_prob.reshape(1,-1)

array([[0.52802946, 0.49516653, 0.45703306, 0.27712052, 0.34390047,
        0.26825171, 0.27712052, 0.607686  , 0.42836534, 0.43637155,
        0.31387455, 0.23676248, 0.45703306, 0.43602768, 0.37596116,
        0.44900317, 0.46952365, 0.68521935, 0.25167254, 0.47073304,
        0.42361093, 0.56580644, 0.52792177, 0.40302605, 0.27457435]])

In [19]:
dict = {1:"Name",2:"Shubhi",3:"Agarwal"}
print("Name" in dict)

False
